pipeline{
    
    agent any
    stages{
        
        stage('Compile stage'){
            
            steps{
            
            bat 'mvn -f jenkinsCICD/pom.xml clean install'
            }

            }
        stage('Deploy stage'){
            
            step{
                
                bat '''copy C:\\Users\\Mayuresh.Marathe\\git\\JenkinsCICDExample\\jenkinsCICD\\target\\*.war C:\\Users\\Mayuresh.Marathe\\Desktop\\apache-tomcat-8.5.54\\webapps'''
            }
        

        }

    

}
